name: Test

on: [pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install poetry==1.1.11
        poetry config virtualenvs.in-project true
        poetry install --no-dev

    - name: Send Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        poetry run python -m gs_reminder -r ${{ github.repository }} -u ./examples/username.json
